name: Збірка і ПУш у докер хаб

on: 
  push: 
    branches: ["master", "main"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: 1.Завантажити код на репо
        uses: actions/checkout@v3

      - name: 2.Логін у докер хаб
        uses: docker/login-action@v2
        with:
          # ПЕРЕВІРТЕ: назва секрету в GitHub має бути ТОЧНО такою ж
          username: ${{ secrets.Docker_Name }}
          password: ${{ secrets.Docker_Password }}

      - name: 3.Зібрати і відправити у Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          # Якщо DockerFile лежить у тій самій папці, де ви робили git init:
          file: ./DockerFile
          push: true
          # Важливо: жодних пробілів навколо слеша
          tags: ${{ secrets.Docker_Name }}/gametracker:v${{ github.run_number }}
