name: Збірка і ПУш у докер хаб
on: 
  push: 
    branches: ["master","main"]

jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - name: 1.Завантажити код на репо
          uses: actions/checkout@v3

        - name: 2.Логін у докер хаб
          uses: docker/login-action@v2
          with:
            username:${{secrets.Docker_Name}}
            passwoed:${{secrets.Docker_Password}}

        - name: 3.Зібрати і відправити у Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Lesson_6(GameTracker)\Lesson_6(GameTracker)/DockerFile
            push: true
            tags: ${{secrets.Docker_Name}}/gametracker:v${{github.run_number}}
