name: Збірка і ПУш у докер хаб

on: 
  push: 
    branches: ["master", "main"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: 1.Завантажити код на репо
        uses: actions/checkout@v3

      - name: 2.Логін у докер хаб
        uses: docker/login-action@v2
        with:
          # Обов'язково з пробілом після двокрапки
          username: ${{ secrets.Docker_Name }}
          password: ${{ secrets.Docker_Password }}

      - name: 3.Зібрати і відправити у Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          # Шлях до Dockerfile з використанням прямих слешів
          file: ./Контейнеризація та оркестрація додатків Docker, Kubernetes\Lesson_6/Lesson_6(GameTracker)/Lesson_6(GameTracker)/DockerFile
          push: true
          # Виправлено: без пробілів навколо / та без зайвої } у кінці
          tags: ${{ secrets.Docker_Name }}/gametracker:v${{ github.run_number }}
